2019-12-18 22:35:19,507 ERROR: Exception on /index [GET] [in /Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/yutong/Flask_Mega_Project/app/routes.py", line 38, in index
    prev_url=prev_url)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/yutong/Flask_Mega_Project/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/Users/yutong/Flask_Mega_Project/app/templates/index.html", line 17, in root
    <span aria-hidden="true">&larr;</span> Newer posts
  File "/Users/yutong/Flask_Mega_Project/app/templates/base.html", line 14, in root
    <div class="navbar-header">
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 10, in root
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block_doc
    {% block body -%}
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 39, in block_html
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 92, in block_body
  File "/Users/yutong/Flask_Mega_Project/app/templates/base.html", line 81, in block_content
  File "/Users/yutong/Flask_Mega_Project/app/templates/index.html", line 43, in block_app_content
  File "/Users/yutong/Flask_Mega_Project/app/templates/_post.html", line 18, in root
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/jinja2/runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/jinja2/runtime.py", line 630, in _fail_with_undefined_error
    raise self._undefined_exception(hint)
jinja2.exceptions.UndefinedError: 'flask_moment._moment object' has no attribute 'formNow'
2019-12-18 22:35:20,639 ERROR: Exception on /explore [GET] [in /Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/yutong/Flask_Mega_Project/app/routes.py", line 52, in explore
    next_url=next_url, prev_url=prev_url)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/yutong/Flask_Mega_Project/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/Users/yutong/Flask_Mega_Project/app/templates/index.html", line 17, in root
    <span aria-hidden="true">&larr;</span> Newer posts
  File "/Users/yutong/Flask_Mega_Project/app/templates/base.html", line 14, in root
    <div class="navbar-header">
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 10, in root
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block_doc
    {% block body -%}
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 39, in block_html
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 92, in block_body
  File "/Users/yutong/Flask_Mega_Project/app/templates/base.html", line 81, in block_content
  File "/Users/yutong/Flask_Mega_Project/app/templates/index.html", line 43, in block_app_content
  File "/Users/yutong/Flask_Mega_Project/app/templates/_post.html", line 18, in root
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/jinja2/runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/jinja2/runtime.py", line 630, in _fail_with_undefined_error
    raise self._undefined_exception(hint)
jinja2.exceptions.UndefinedError: 'flask_moment._moment object' has no attribute 'formNow'
2019-12-18 22:37:59,673 INFO: Flask Blog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:52]
2019-12-18 23:12:23,175 INFO: Flask Blog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:54]
2019-12-18 23:16:53,740 INFO: Flask Blog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:54]
2019-12-18 23:18:04,624 INFO: Flask Blog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:54]
2019-12-18 23:18:15,699 INFO: Flask Blog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:54]
2019-12-18 23:35:24,844 INFO: Flask Blog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:54]
2019-12-18 23:35:35,431 INFO: Flask Blog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:54]
2019-12-19 00:17:27,262 INFO: Flask Blog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:54]
2019-12-19 00:25:09,235 INFO: Flask Blog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:54]
2019-12-19 00:25:26,669 INFO: Flask Blog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:54]
2019-12-19 00:26:13,898 INFO: Flask Blog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:54]
2019-12-19 00:26:17,712 INFO: Flask Blog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:54]
2019-12-19 00:26:32,206 INFO: Flask Blog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:54]
2019-12-19 00:26:40,955 INFO: Flask Blog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:54]
