2019-12-19 22:57:17,072 ERROR: Exception on /search [GET] [in /Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/yutong/Flask_Mega_Project/app/main/routes.py", line 145, in search
    posts, total = Post.search(g.search_from.q.data, page, current_app.config['POST_PER_PAGE'])
AttributeError: type object 'Post' has no attribute 'search'
2019-12-19 23:03:43,718 INFO: Flask Blog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:73]
2019-12-19 23:03:46,487 ERROR: Exception on /search [GET] [in /Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/yutong/Flask_Mega_Project/app/main/routes.py", line 145, in search
    posts, total = Post.search(g.search_form.q.data, page,
AttributeError: type object 'Post' has no attribute 'search'
2019-12-19 23:03:57,067 ERROR: Exception on /search [GET] [in /Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/yutong/Flask_Mega_Project/app/main/routes.py", line 145, in search
    posts, total = Post.search(g.search_form.q.data, page,
AttributeError: type object 'Post' has no attribute 'search'
2019-12-19 23:05:14,755 INFO: Flask Blog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:73]
2019-12-19 23:05:25,104 ERROR: Exception on /search [GET] [in /Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/yutong/Flask_Mega_Project/app/main/routes.py", line 145, in search
    posts, total = Post.search(g.search_form.q.data, page,
AttributeError: type object 'Post' has no attribute 'search'
2019-12-19 23:10:19,179 INFO: Flask Blog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:73]
2019-12-19 23:11:18,510 INFO: Flask Blog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:73]
2019-12-19 23:11:38,935 INFO: Flask Blog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:73]
2019-12-19 23:11:50,884 ERROR: Exception on /search [GET] [in /Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/yutong/Flask_Mega_Project/app/main/routes.py", line 146, in search
    current_app.config['POSTS_PER_PAGE'])
  File "/Users/yutong/Flask_Mega_Project/app/models.py", line 23, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/Users/yutong/Flask_Mega_Project/app/search.py", line 23, in query_index
    'form': (page - 1) * per_page, 'size': perpage})
NameError: name 'perpage' is not defined
2019-12-19 23:11:55,483 ERROR: Exception on /search [GET] [in /Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/yutong/Flask_Mega_Project/app/main/routes.py", line 146, in search
    current_app.config['POSTS_PER_PAGE'])
  File "/Users/yutong/Flask_Mega_Project/app/models.py", line 23, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/Users/yutong/Flask_Mega_Project/app/search.py", line 23, in query_index
    'form': (page - 1) * per_page, 'size': perpage})
NameError: name 'perpage' is not defined
2019-12-19 23:13:19,711 INFO: Flask Blog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:73]
