2019-12-19 22:31:34,727 INFO: Flask Blog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:73]
2019-12-19 22:31:46,119 INFO: Flask Blog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:73]
2019-12-19 22:31:55,579 INFO: Flask Blog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:73]
2019-12-19 22:33:38,494 INFO: Flask Blog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:73]
2019-12-19 22:33:52,337 INFO: Flask Blog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:73]
2019-12-19 22:54:19,250 INFO: Flask Blog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:73]
2019-12-19 22:54:29,456 ERROR: Exception on /index [GET] [in /Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1947, in full_dispatch_request
    rv = self.preprocess_request()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 2241, in preprocess_request
    rv = func()
  File "/Users/yutong/Flask_Mega_Project/app/main/routes.py", line 21, in before_request
    g.search_form = SearchForm()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/yutong/Flask_Mega_Project/app/main/forms.py", line 36, in __init__
    kwargs['formdata'] = request.qrgs
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'qrgs'
2019-12-19 22:54:30,869 ERROR: Exception on /index [GET] [in /Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1947, in full_dispatch_request
    rv = self.preprocess_request()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 2241, in preprocess_request
    rv = func()
  File "/Users/yutong/Flask_Mega_Project/app/main/routes.py", line 21, in before_request
    g.search_form = SearchForm()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/yutong/Flask_Mega_Project/app/main/forms.py", line 36, in __init__
    kwargs['formdata'] = request.qrgs
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'qrgs'
2019-12-19 22:54:42,825 INFO: Flask Blog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:73]
2019-12-19 22:54:45,486 ERROR: Exception on /index [GET] [in /Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1947, in full_dispatch_request
    rv = self.preprocess_request()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 2241, in preprocess_request
    rv = func()
  File "/Users/yutong/Flask_Mega_Project/app/main/routes.py", line 21, in before_request
    g.search_form = SearchForm()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/yutong/Flask_Mega_Project/app/main/forms.py", line 36, in __init__
    kwargs['formdata'] = request.qrgs
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'qrgs'
2019-12-19 22:54:46,456 ERROR: Exception on /index [GET] [in /Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1947, in full_dispatch_request
    rv = self.preprocess_request()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 2241, in preprocess_request
    rv = func()
  File "/Users/yutong/Flask_Mega_Project/app/main/routes.py", line 21, in before_request
    g.search_form = SearchForm()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/yutong/Flask_Mega_Project/app/main/forms.py", line 36, in __init__
    kwargs['formdata'] = request.qrgs
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'qrgs'
2019-12-19 22:54:47,501 ERROR: Exception on /index [GET] [in /Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1947, in full_dispatch_request
    rv = self.preprocess_request()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 2241, in preprocess_request
    rv = func()
  File "/Users/yutong/Flask_Mega_Project/app/main/routes.py", line 21, in before_request
    g.search_form = SearchForm()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/yutong/Flask_Mega_Project/app/main/forms.py", line 36, in __init__
    kwargs['formdata'] = request.qrgs
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'qrgs'
2019-12-19 22:57:00,987 INFO: Flask Blog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:73]
