2019-12-18 15:30:26,730 ERROR: Exception on /login [GET] [in /Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yutong/Flask_Mega_Project/app/routes.py", line 71, in login
    page, app.config['POST_PER_PAGE'], False
KeyError: 'POST_PER_PAGE'
2019-12-18 15:30:46,726 INFO: Microblog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:43]
2019-12-18 15:31:43,949 INFO: Microblog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:43]
2019-12-18 15:32:49,023 INFO: Microblog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:43]
2019-12-18 15:33:50,519 INFO: Microblog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:43]
