2019-12-18 13:03:33,138 INFO: Microblog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:43]
2019-12-18 13:03:55,573 INFO: Microblog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:43]
2019-12-18 13:36:03,288 INFO: Microblog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:43]
2019-12-18 13:40:13,198 INFO: Microblog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:43]
2019-12-18 14:10:44,603 INFO: Microblog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:43]
2019-12-18 14:19:01,931 INFO: Microblog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:43]
2019-12-18 14:19:47,290 INFO: Microblog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:43]
2019-12-18 14:20:38,077 INFO: Microblog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:43]
2019-12-18 15:11:07,698 INFO: Microblog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:43]
2019-12-18 15:12:14,751 INFO: Microblog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:43]
2019-12-18 15:13:49,080 INFO: Microblog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:43]
2019-12-18 15:18:44,704 INFO: Microblog startup [in /Users/yutong/Flask_Mega_Project/app/__init__.py:43]
2019-12-18 15:18:54,702 ERROR: Exception on /index [GET] [in /Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/yutong/Flask_Mega_Project/app/routes.py", line 31, in index
    page, app.config['POST_PER_PAGE'], False
KeyError: 'POST_PER_PAGE'
2019-12-18 15:18:57,196 ERROR: Exception on /index [GET] [in /Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/yutong/Flask_Mega_Project/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/yutong/Flask_Mega_Project/app/routes.py", line 31, in index
    page, app.config['POST_PER_PAGE'], False
KeyError: 'POST_PER_PAGE'
